apiVersion: v1
kind: Service
metadata:
  name: udgram-api-feed
  labels:
    run: udgram-api-feed
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: udgram-api-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}