apiVersion: v1
kind: Service
metadata:
  name:  reverseproxy
  labels:
    app: reverseproxy
spec:
  ports:
  - port: 8080
    name: '8080'
    protocol: TCP
    targetPort: 8080
  selector:
    app: reverseproxy
    apiVersion: v1